# Compilación y Pruebas Proyecto Java
name: Compilación Java

on:
  # se ejecuta el flujo con cada push y pull request
  # o haciendo clic desde las opciones de Github Actions
  [push, pull_request, workflow_dispatch]
  
jobs:
  build:
  
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java: [ 11, 12, 17 ]

    # se ejecuta en Ubuntu Linux
    runs-on: ${{ matrix.os }}

    # acciones a ejecutar
    steps:
    - name: Descarga el código fuente
      uses: actions/checkout@v2
    
    - name: Configura JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: ${{ matrix.java }}

    - name: Compila el proyecto
      run: mvn -B package --file pom.xml
Revise la ejecución de los flujos de trabajo. Note que se inicia la ejecución de 9 flujos de trabajo, uno con cada combinación de sistema operativo y versión de Java.

Al hacer clic en la cantidad de trabajos, es posible ver el detalle de cada flujo. Note que se pueden ver todos los flujos, con las combinaciones de sistema operativo y de versión de Java.

Back
